### PR TITLE
Semi lock and unlock states.

### PR DESCRIPTION
**Pull request by organom**
Added the semi lock and unlock states. Issue #3 

But I'm still missing a way to enter and exit the SEMI mode. Should we do this by another button near the rasp board, or by a combination of keys on the keypad?

### CODE REVIEW

**Comment by tiefpunkt** [comment]
Nice start, but I'd like to have the timeout for locking the door again handled by the backend, not the frontend. That makes it easier to adjust stuff later on.

@peterfroehlich, how can we update the firmware of the frontend?

**Comment by tiefpunkt** [comment]
Oh, also, regarding the way to enter SEMI mode, i'd like to use a rotating switch on the backend panel.

**Comment by organom** [comment]
Agree with the button on the big box :D we can then hock the modes fastly into the right pins. About the backend timeout it makes sense, just did it in the front end because there was already code like that (I can make the change later today) :P 

Please feel free to add the code to the rotating switch to branch so that then we can merge the pull request with the entire functionality working :)   

PS: Also, we have to test it before the merging, heheheh

**Comment by tiefpunkt** [comment]
here we go, maybe I can test it later

**Pull request merged**
